### ISSUE TITLE
Can't Run Command From magerun-addons

### ISSUE THREAD

**Issue by astorm** [philwinkle/unhack-core#3]
Tried running the command as per the docs and got the following

```
$ n98-magerun.phar diff:files --line-number=1                                              
[RuntimeException]                          
The "--line-number" option does not exist.  
```

Docs should be updated to indicate the correct `magerun-addons` branch **or** the `magerun-addons` should be merged into master **or** (ideally) `unhack-core` should include its own diff implementation.  Relying on a command from a separate project is a good "1.0, get it out there" sort of thing, but if this is going to be more than a promotional novelty it should be able to run by itself.

**Comment by kirkmadera** [comment]
I just figured this out also. You have to use the unhack_core branch of magerun-addons. Phil, can you make a composer.json for this (and maybe submit it to Packagist when it's stable enough)?

Something like this:

```
{
    "name": "philwinkle/unhack-core",
    "description": "N98 MageRun module to unhack Magento core code.",
    "type": "library",
    "keywords": ["magerun"],
    "homepage": "https://github.com/philwinkle/unhack-core",
    "minimum-stability": "dev",
    "license": "MIT",
    "authors": [
        {
            "name": "Phil Winkle",
            "email": "philwinkle@gmail.com",
            "homepage": "http://blog.philwinkle.com/",
            "role": "Developer"
        }
    ],
    "require": {
        "php": ">=5.3.0"
    },
    "require": {
        "n98/magerun": "1.91.*",
        "kalenjordan/magerun-addons": "dev-unhack_core"
    },
    "autoload": {
        "psr-0": {
            "Philwinkle": "src/"
        }
    }
}
```

**Comment by philwinkle** [comment]
@astorm sorry for radio silence, I didn't have notifications for this repo enabled. 

You're 100% correct. @kalenjordan already had this feature in magerun and we utilized it. I would like to make it less of a requirement and have the help return a sample GNU diff format that will work. 

Happy to accept the PR from @kirkmadera if you could move the composer.json to its own PR.

**Comment by philwinkle** [comment]
PR for this feature to master @kalenjordan https://github.com/kalenjordan/magerun-addons/pull/20

**Comment by kalenjordan** [comment]
I thought I already merged to  master - will check that out tomorrow.

**Comment by kalenjordan** [comment]
I merged the core unhack stuff to master back on Oct 29:
https://github.com/kalenjordan/magerun-addons/commit/aee8f22a12dfa61b9e449f0731e162d07544eb0d

**Comment by philwinkle** [comment]
Weird. Wasn't coming up for Alan Storm or Kirk Madira. The PR you merged
earlier seems to fix it?

**Comment by kalenjordan** [comment]
Maybe I merged it locally and we did the testing on my local master but I
hadn't pushed it up yet until yesterday when I pushed up some other stuff
to magerun-addons on master?

On Wed, Nov 11, 2015 at 4:04 PM, Phillip Jackson notifications@github.com
wrote:

> Weird. Wasn't coming up for Alan Storm or Kirk Madira. The PR you merged
> earlier seems to fix it?
> On Nov 11, 2015 7:01 PM, "kalenjordan" notifications@github.com wrote:
> 
> > I merged the core unhack stuff to master back on Oct 29:
> > kalenjordan/magerun-addons@aee8f22
> > <
> > https://github.com/kalenjordan/magerun-addons/commit/aee8f22a12dfa61b9e449f0731e162d07544eb0d
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/philwinkle/unhack-core/issues/3#issuecomment-155949274>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/philwinkle/unhack-core/issues/3#issuecomment-155951029
> .

## 

Kalen Jordan
Founder, MageMail

Listen to MageTalk - The Magento Podcast http://magetalk.com/ | MageMail
- The Triggered Email App for Magento
  http://magemail.co/?utm_medium=email&utm_source=signature&utm_campaign=signature

**Comment by philwinkle** [comment]
I think that was the issue. Good call. Glad it's resolved.
